Repository freeipa/freeipa-webui, pull requests merged in 2023-12, with the labels that each got.

#186 Fix: Replace Mac-OS runner by Ubuntu
  .github/workflows/gating.yml
  Vagrantfile
Labels: tests

#209 Create stale.yml
  .github/workflows/stale.yml
Labels: ack

#211 Update stale.yml to mark issues after 365 days
  .github/workflows/stale.yml
Labels: ack

#187 Normalize User object
  src/components/Form/IpaCalendar.tsx
  src/components/UserSettings.tsx
  src/hooks/useUserSettingsData.tsx
  src/services/rpc.ts
  src/store/store.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/krbPolicyUtils.tsx
  src/utils/pwPolicyUtils.tsx
  src/utils/userUtils.tsx
  src/utils/utils.tsx
Labels: needs-review

#196 Add new params into 'User' data type
  src/store/Identity/activeUsers-slice.ts
  src/store/Identity/preservedUsers-slice.ts
  src/store/Identity/preservedUsers.json
  src/store/Identity/stageUsers-slice.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/userUtils.tsx
Labels: needs-review
