Repository freeipa/freeipa-webui, pull requests merged in 2024-07, with the labels that each got.

#445 Fix breadcrumbs not showing links
  src/components/UserSettings.tsx
  src/components/layouts/BreadCrumb.tsx
  src/hooks/useUpdateRoute.tsx
  src/pages/ActiveUsers/ActiveUsersTabs.tsx
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/pages/Hosts/HostsTabs.tsx
  src/pages/PreservedUsers/PreservedUsersTabs.tsx
  src/pages/Services/ServicesTabs.tsx
  src/pages/StageUsers/StageUsersTabs.tsx
Labels: needs-review

#448 Issue 447 - Improve empty table handling
  src/components/layouts/SettingsTableLayout.tsx
  src/components/layouts/TableLayout.tsx
  src/components/tables/EmptyBodyTable.tsx
Labels: ack, needs-review

#444 [Services] Implement 'Is managed by' section
  src/components/ManagedBy/ManagedByHosts.tsx
  src/pages/Services/ServicesManagedBy.tsx
  src/services/rpcServices.ts
Labels: ack

#446 [Services] Fix URL not being loaded on refresh
  src/pages/Services/ServicesManagedBy.tsx
  src/pages/Services/ServicesMemberOf.tsx
  src/pages/Services/ServicesSettings.tsx
  src/pages/Services/ServicesTable.tsx
  src/pages/Services/ServicesTabs.tsx
Labels: ack

#449 Fix: Optional membership functionalty in 'Is a member of' > 'Roles' tab
  src/components/MemberOf/MemberOfRoles.tsx
  src/pages/Services/ServicesMemberOf.tsx
Labels: ack

#450 Fix: `page` parameter is not shown when refreshing any 'Is a member of` tab section
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfHostGroups.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
  src/pages/Hosts/HostsMemberOf.tsx
Labels: ack, needs-review

#451 [Services] Add URL params
  src/pages/Services/Services.tsx
  src/pages/Services/ServicesTabs.tsx
Labels: ack

#454 Issue 453 - User Groups - implement settings page
  src/components/modals/ConfirmModal.tsx
  src/hooks/useUserGroupSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/UserGroups/UserGroupsSettings.tsx
  src/pages/UserGroups/UserGroupsTable.tsx
  src/pages/UserGroups/UserGroupsTabs.tsx
  src/services/rpcUserGroups.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/groupUtils.tsx
  src/utils/pwPolicyUtils.tsx
Labels: ack, needs-review

#455 [Groups] Add URL routes in all section pages
  src/pages/HostGroups/HostGroups.tsx
  src/pages/Netgroups/Netgroups.tsx
  src/pages/UserGroups/UserGroups.tsx
Labels: ack

#457 Fix: Redirect to 'NotFound' if page doesn't exist
  src/pages/ActiveUsers/ActiveUsersTabs.tsx
  src/pages/HostGroups/HostGroupsTabs.tsx
  src/pages/Hosts/HostsTabs.tsx
  src/pages/Netgroups/NetgroupsTabs.tsx
  src/pages/PreservedUsers/PreservedUsersTabs.tsx
  src/pages/Services/ServicesTabs.tsx
  src/pages/StageUsers/StageUsersTabs.tsx
  src/pages/UserGroups/UserGroupsTabs.tsx
Labels: ack

#460 Issue 459 - Refactor DeletionConfirmationModal to ConfirmationModal
  src/components/Form/IpaCertificateMappingData.tsx
  src/components/Form/IpaCertificates.tsx
  src/components/Form/IpaSshPublicKeys.tsx
  src/components/Form/PrincipalAliasMultiTextBox.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/ConfirmationModal.tsx
  src/pages/Hosts/HostsSettings.tsx
  src/pages/UserGroups/UserGroupsSettings.tsx
Labels: needs-review

#463 Issue 462 - Implement Host Groups settings page
  src/hooks/useHostGroupSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/HostGroups/HostGroupsSettings.tsx
  src/pages/HostGroups/HostGroupsTable.tsx
  src/pages/HostGroups/HostGroupsTabs.tsx
  src/pages/UserGroups/UserGroupsSettings.tsx
  src/pages/UserGroups/UserGroupsTabs.tsx
  src/services/rpcHostGroups.ts
Labels: needs-review

#464 Fix: Datetimes not refreshed on incorrect values
  src/components/Form/DateTimeSelector.tsx
Labels: needs-review

#467 Fix: Apache regex configuration
  Vagrantfile
Labels: needs-review

#461 Issue 458 - Services - implement kebab
  src/components/modals/IssueNewCertificate.tsx
  src/pages/Services/ServicesSettings.tsx
  src/services/rpcServices.ts
Labels: needs-review

#471 Issue 458 - Services - fix kebab regression
  src/pages/Services/ServicesSettings.tsx
Labels: ack

#470 Issue 469 - Fix keytab table URL links
  src/components/tables/KeytabTable.tsx
Labels: ack

#473 Add tests for Usergroups settings page
  tests/features/steps/common.ts
  tests/features/usergroup_settings_handling.feature
Labels: needs-review, tests

#477 [User groups][Members] Implement the 'Services' tab section
  src/components/Members/MemberTable.tsx
  src/components/Members/MembersServices.tsx
  src/navigation/AppRoutes.tsx
  src/pages/UserGroups/UserGroupsMembers.tsx
  src/services/rpcServices.ts
Labels: ack

#474 Implement login page basic layout + logic
  src/App.tsx
  src/assets/images/login-screen-background.jpg
  src/assets/images/login-screen-logo.png
  src/components/layouts/DataSpinner.tsx
  src/login/LoginMainPage.tsx
  src/navigation/AppRoutes.tsx
  src/store/Global/auth-slice.ts
  src/store/store.ts
Labels: ack

#481 Implement a Dual List Selector layout component
  src/components/layouts/DualListLayout.tsx
  src/components/tables/KeytabTable.tsx
  src/services/rpcSettings.ts
Labels: needs-review

#475 Issue 466 - Netgroups - implement settings page
  src/components/Form/IpaCheckbox.tsx
  src/components/layouts/DualListLayout.tsx
  src/components/layouts/SettingsTableLayout.tsx
  src/components/modals/RemoveNetgroupMembers.tsx
  src/hooks/useNetgroupSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/Netgroups/NetgroupsMemberTable.tsx
  src/pages/Netgroups/NetgroupsSettings.tsx
  src/pages/Netgroups/NetgroupsTable.tsx
  src/pages/Netgroups/NetgroupsTabs.tsx
  src/services/rpcNetgroups.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/netgroupsUtils.tsx
  tests/features/netgroup_settings_handling.feature
  tests/features/steps/common.ts
Labels: needs-review

#479 [User groups][Members] Implement the 'External' tab section
  src/components/Members/MemberTable.tsx
  src/components/Members/MembersExternal.tsx
  src/navigation/AppRoutes.tsx
  src/pages/UserGroups/UserGroupsMembers.tsx
  src/services/rpcUserGroups.ts
  src/utils/groupUtils.tsx
Labels: ack

#482 Issue 478 - ID Views - implement main page and buttons
  src/components/BulkSelectorIDViewsPrep.tsx
  src/components/layouts/DualListLayout.tsx
  src/components/modals/AddIDView.tsx
  src/components/modals/DeleteIDViews.tsx
  src/components/tables/DeletedElementsTable.tsx
  src/components/tables/KeytabTable.tsx
  src/hooks/useIDViewSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/IDViews/IDViews.tsx
  src/pages/IDViews/IDViewsSettings.tsx
  src/pages/IDViews/IDViewsTable.tsx
  src/pages/IDViews/IDViewsTabs.tsx
  src/pages/Netgroups/NetgroupsMemberTable.tsx
  src/services/rpc.ts
  src/services/rpcIDViews.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/idViewUtils.tsx
  src/utils/utils.tsx
  tests/features/id_view_handling.feature
  tests/features/steps/common.ts
Labels: needs-review

#483 Implement user + password authentication mechanism
  src/App.tsx
  src/AppLayout.tsx
  src/login/LoginMainPage.tsx
  src/navigation/AppRoutes.tsx
  src/services/rpcAuth.ts
Labels: ack, needs-review

#487 Improve DualList searching
  src/components/layouts/DualListLayout.tsx
Labels: ack

#488 Fix netgroup settings handling for Allow anyone/host
  src/pages/Netgroups/NetgroupsMemberTable.tsx
  src/pages/Netgroups/NetgroupsSettings.tsx
  src/services/rpcNetgroups.ts
  tests/features/netgroup_settings_handling.feature
Labels: needs-review

#493 Implement HBAC services settings page
  src/hooks/useHBACServiceSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/HBACServices/HBACServicesSettings.tsx
  src/pages/HBACServices/HBACServicesTable.tsx
  src/pages/HBACServices/HBACServicesTabs.tsx
  src/services/rpcHBAC.ts
  src/utils/hbacServicesUtils.tsx
  tests/features/hbacsvc_settings_handling.feature
Labels: needs-review

#495 Implement HBAC server groups settings page
  src/hooks/useHBACServiceGrpSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsSettings.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsTable.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsTabs.tsx
  src/services/rpc.ts
  src/services/rpcHBAC.ts
  src/utils/hbacServiceGrpUtils.tsx
  tests/features/hbacsvcgrp_settings_handling.feature
Labels: needs-review
