Repository freeipa/freeipa-webui, pull requests merged in 2024-09, with the labels that each got.

#534 Fix: incorrect fields shown in reset password forms
  src/components/modals/UserModals/ResetPassword.tsx
  src/store/Global/global-slice.ts
Labels: ack, needs-review

#538 Fix: Not rely on error messages when user is not logged out
  src/login/LoginMainPage.tsx
  src/login/ResetPasswordPage.tsx
  src/pages/ActiveUsers/ActiveUsers.tsx
  src/pages/HBACRules/HBACRules.tsx
  src/pages/HBACServiceGroups/HBACServiceGroups.tsx
  src/pages/HBACServices/HBACServices.tsx
  src/pages/HostGroups/HostGroups.tsx
  src/pages/Hosts/Hosts.tsx
  src/pages/IDViews/IDViews.tsx
  src/pages/Netgroups/Netgroups.tsx
  src/pages/PreservedUsers/PreservedUsers.tsx
  src/pages/Services/Services.tsx
  src/pages/StageUsers/StageUsers.tsx
  src/pages/SudoCmdGroups/SudoCmdGroups.tsx
  src/pages/SudoCmds/SudoCmds.tsx
  src/pages/SudoRules/SudoRules.tsx
  src/pages/UserGroups/UserGroups.tsx
Labels: needs-review

#537 Autofill new certificate instructions
  src/components/modals/CertificateModals/IssueNewCertificate.tsx
Labels: ack

#532 Member - fix issues with indirect/direct member tab counts
  src/components/Members/MembersServices.tsx
  src/components/Members/MembersUserGroups.tsx
  src/components/Members/MembersUsers.tsx
  src/pages/UserGroups/UserGroupsMembers.tsx
  src/pages/UserGroups/UserGroupsTabs.tsx
Labels: ack

#540 Fix memberOf counters
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfHostGroups.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
  src/components/Members/MembersServices.tsx
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/pages/UserGroups/UserGroupsMemberOf.tsx
Labels: needs-review

#553 [Netgroups][Is a member of] Implement 'Netgroups' tab section
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/navigation/AppRoutes.tsx
  src/pages/HostGroups/HostGroupsMemberOf.tsx
  src/pages/Netgroups/NetgroupsMemberOf.tsx
  src/pages/Netgroups/NetgroupsTabs.tsx
  tests/features/netgroup_memberof.feature
  tests/features/steps/common.ts
Labels: ack, needs-review

#559 Implement HBAC service memberOf page
  src/components/MemberOf/MemberOfHbacServiceGroups.tsx
  src/navigation/AppRoutes.tsx
  src/pages/HBACServices/HBACServicesMemberOf.tsx
  src/pages/HBACServices/HBACServicesTabs.tsx
  src/services/rpcHBACSvcGroups.ts
  tests/features/hbacsvc_is_member_of.feature
Labels: ack

#563 Implement HBAC service groups Member page
  src/components/Members/MembersHbacServices.tsx
  src/navigation/AppRoutes.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsMembers.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsTabs.tsx
  src/pages/HBACServices/HBACServicesMemberOf.tsx
  src/services/rpcHBACServices.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/hbacServiceGrpUtils.tsx
  tests/features/hbac_svc_grp_members.feature
Labels: ack

#566 Implement sudo command group members page
  src/components/Members/MembersSudoCommands.tsx
  src/components/tables/DeletedElementsTable.tsx
  src/navigation/AppRoutes.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsMembers.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsTabs.tsx
  src/services/rpcSudoCmdGroups.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/sudoCmdGroupsUtils.tsx
  tests/features/sudo_cmd_groups_members.feature
Labels: ack

#569 WA: Downgrade runner version
  .github/workflows/gating.yml
Labels: needs-review

#571 Implement the Configuration page
  src/components/Form/IpaDropdownSearch.tsx
  src/components/Form/IpaNumberInput.tsx
  src/components/layouts/PopoverWithIconLayout.tsx
  src/hooks/useConfigSettingsData.tsx
  src/hooks/useSudoRuleSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/navigation/NavRoutes.ts
  src/pages/Configuration/ConfigGroupOptions.tsx
  src/pages/Configuration/ConfigObjectclassTable.tsx
  src/pages/Configuration/ConfigSELinuxOptions.tsx
  src/pages/Configuration/ConfigSearchOptions.tsx
  src/pages/Configuration/ConfigServerOptions.tsx
  src/pages/Configuration/ConfigServiceOptions.tsx
  src/pages/Configuration/ConfigUserOptions.tsx
  src/pages/Configuration/Configuration.tsx
  src/services/rpc.ts
  src/services/rpcConfig.ts
  src/utils/configUtils.tsx
  src/utils/datatypes/globalDataTypes.ts
  tests/features/configuration_handling.feature
  tests/features/steps/common.ts
Labels: needs-review
