Repository freeipa/freeipa-webui, pull requests merged in 2024-04, with the labels that each got.

#327 [Integration tests] Textboxes with buttons
  tests/features/steps/common.ts
  tests/features/user_details.feature
Labels: ack

#331 Issue 330 - Add tests for Hosts page
  src/components/modals/AddHost.tsx
  tests/features/host_handling.feature
  tests/features/steps/common.ts
Labels: ack, tests

#347 Reset page when changing membership type
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
Labels: bug

#343 [Integration tests] 'Is a member of' section
  src/components/MemberOf/MemberOfTableUserGroups.tsx
  tests/features/steps/common.ts
  tests/features/steps/user_handling.ts
  tests/features/user_is_member_of.feature
Labels: ack, tests

#350 Fix available elements not shown in add
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/hooks/useUserMemberOfData.tsx
Labels: bug, ack
