Repository freeipa/freeipa-webui, pull requests merged in 2024-05, with the labels that each got.

#359 [Is a member of][HBAC rules] 'Refresh' button functionality
  src/components/MemberOf/MemberOfHbacRules.tsx
Labels: ack

#349 Issue 332 [Integration tests] - add tests for Services table
  tests/features/service_handling.feature
  tests/features/steps/common.ts
Labels: ack, tests

#370 package.json: Add alias to verify and clean the cache
  package.json
Labels: enhancement, ack, needs-review

#372 Fix: ariaLabel for password and krb5 principal expiration datepicker
  src/components/Form/IpaCalendar.tsx
  src/components/UsersSections/UsersAccountSettings.tsx
  src/utils/ipaObjectUtils.ts
Labels: ack

#375 Feat: Show fixed amount of asterisks if the user has password
  src/components/UserSettings.tsx
  src/components/UsersSections/UsersAccountSettings.tsx
  src/components/modals/ResetPassword.tsx
Labels: ack

#377 Cypress: Enable experimental memory management
  cypress/cypress.config.ts
Labels: ack

#381 Simplify has_password checking in user settings
  src/components/UsersSections/UsersAccountSettings.tsx
Labels: ack

#382 Unit testing: Include jest in gating tests
  .github/workflows/gating.yml
Labels: ack, tests

#380 Refactor IpaTextInput component
  src/components/Form/IpaTextInput.tsx
  src/components/HostsSections/HostSettings.tsx
  src/components/UsersSections/UsersAccountSettings.tsx
  src/components/UsersSections/UsersAttributesSMB.tsx
  src/components/UsersSections/UsersEmployeeInfo.tsx
  src/components/UsersSections/UsersIdentity.tsx
  src/components/UsersSections/UsersMailingAddress.tsx
Labels: ack

#385 gating.yaml: Upgrade actions to supported versions
  .github/workflows/gating.yml
Labels: ack, tests

#393 [Is a member of][Suboradinate IDs] Sync table data
  src/components/MemberOf/MemberOfSubIdToolbar.tsx
  src/components/MemberOf/MemberOfSubIds.tsx
  src/components/MemberOf/MemberOfTableSubIds.tsx
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/services/rpcSubIds.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/subIdsUtils.ts
  src/utils/userUtils.tsx
Labels: ack, needs-review

#398 [Is a member of][Subordinate IDs] 'Auto assign subordinate IDs' button
  src/components/MemberOf/MemberOfSubIds.tsx
  src/services/rpcSubIds.ts
Labels: needs-review
