Repository freeipa/freeipa-webui, pull requests merged in 2024-08, with the labels that each got.

#501 ID Views - implement settings page
  src/components/layouts/TitleLayout.tsx
  src/navigation/AppRoutes.tsx
  src/pages/ActiveUsers/ActiveUsersTabs.tsx
  src/pages/HBACRules/HBACRulesTabs.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsTabs.tsx
  src/pages/HBACServices/HBACServicesTabs.tsx
  src/pages/HostGroups/HostGroupsTabs.tsx
  src/pages/Hosts/HostsTabs.tsx
  src/pages/IDViews/IDViewsSettings.tsx
  src/pages/IDViews/IDViewsTable.tsx
  src/pages/IDViews/IDViewsTabs.tsx
  src/pages/Netgroups/NetgroupsTabs.tsx
  src/pages/PreservedUsers/PreservedUsersTabs.tsx
  src/pages/Services/ServicesTabs.tsx
  src/pages/StageUsers/StageUsersTabs.tsx
  src/pages/UserGroups/UserGroupsTabs.tsx
  src/utils/datatypes/globalDataTypes.ts
  src/utils/idViewUtils.tsx
  tests/features/id_view_settings_handling.feature
Labels: needs-review

#498 UserGroups - Implement memberOf tab
  src/components/MemberOf/MemberOfTableUserGroups.tsx
  src/navigation/AppRoutes.tsx
  src/pages/UserGroups/UserGroupsMemberOf.tsx
  src/pages/UserGroups/UserGroupsTabs.tsx
  src/services/rpcHBAC.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/groupUtils.tsx
  tests/features/usergroup_is_member_of.feature
Labels: needs-review

#489 Login kerberos authentication method
  src/login/LoginMainPage.tsx
  src/services/rpc.ts
  src/services/rpcAuth.ts
Labels: needs-review

#513 Make all memberOf dialogs and alerts consistent
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfHostGroups.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
  tests/features/user_is_member_of.feature
  tests/features/usergroup_is_member_of.feature
Labels: needs-review

#514 Calulate membership count when rendering
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/Hosts/HostsManagedBy.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/pages/Services/ServicesManagedBy.tsx
  src/pages/Services/ServicesMemberOf.tsx
  src/pages/UserGroups/UserGroupsMemberOf.tsx
Labels: needs-review

#505 Sudo commands - implement main page and buttons
  src/components/BulkSelectorSudoCmdsPrep.tsx
  src/components/modals/AddSudoCmd.tsx
  src/components/modals/DeleteSudoCmd.tsx
  src/components/tables/DeletedElementsTable.tsx
  src/navigation/AppRoutes.tsx
  src/pages/SudoCmds/SudoCmds.tsx
  src/pages/SudoCmds/SudoCmdsTable.tsx
  src/pages/SudoCmds/SudoCmdsTabs.tsx
  src/services/rpc.ts
  src/services/rpcSudoCmds.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/sudoCmdsUtils.tsx
  src/utils/utils.tsx
  tests/features/sudo_cmd_handling.feature
Labels: ack, needs-review

#515 Fix usergroup URL handling
  src/pages/UserGroups/UserGroupsTabs.tsx
Labels: ack, needs-review

#507 Sudo command groups - implement main page
  src/components/BulkSelectorSudoCmdGroupsPrep.tsx
  src/components/modals/AddSudoCmdGroup.tsx
  src/components/modals/DeleteSudoCmdGroups.tsx
  src/components/tables/DeletedElementsTable.tsx
  src/pages/SudoCmdGroups/SudoCmdGroups.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsTable.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsTabs.tsx
  src/services/rpc.ts
  src/services/rpcSudoCmdGroups.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/sudoCmdGroupsUtils.tsx
  src/utils/utils.tsx
  tests/features/sudo_cmd_groups_handling.feature
Labels: ack, needs-review

#497 Login via certificate authentication method
  src/login/LoginMainPage.tsx
  src/services/rpcAuth.ts
Labels: needs-review

#523 Implement sudo command group settings
  src/hooks/useSudoCmdGroupsSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsSettings.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsTable.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsTabs.tsx
  src/services/rpc.ts
  src/services/rpcSudoCmdGroups.ts
  tests/features/sudo_cmd_groups_settings_handling.feature
Labels: needs-review

#522 Implement sudo command settings
  src/hooks/useSudoCmdsSettingsData.tsx
  src/pages/SudoCmds/SudoCmdsSettings.tsx
  src/pages/SudoCmds/SudoCmdsTable.tsx
  src/pages/SudoCmds/SudoCmdsTabs.tsx
  src/services/rpc.ts
  src/services/rpcSudoCmds.ts
  tests/features/sudo_cmd_settings_handling.feature
Labels: needs-review

#519 Improve UX when adding/delete members
  src/components/ManagedBy/ManagedByAddModal.tsx
  src/components/ManagedBy/ManagedByDeleteModal.tsx
  src/components/ManagedBy/ManagedByHosts.tsx
  src/components/MemberOf/MemberOfAddModal.tsx
  src/components/MemberOf/MemberOfDeleteModal.tsx
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfHostGroups.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
  src/components/Members/MembersExternal.tsx
  src/components/Members/MembersServices.tsx
  src/components/Members/MembersUserGroups.tsx
  src/components/Members/MembersUsers.tsx
Labels: ack

#528 Adapt tests to new login page
  cypress/cypress.config.ts
  cypress/support/commands.ts
  tests/features/hbacsvcgrp_settings_handling.feature
  tests/features/steps/common.ts
Labels: ack

#525 Use a single BulkSelector component
  src/components/BulkSelectorHBACRulesPrep.tsx
  src/components/BulkSelectorHBACServicesPrep.tsx
  src/components/BulkSelectorHBACSvcGroupPrep.tsx
  src/components/BulkSelectorHostGroupsPrep.tsx
  src/components/BulkSelectorIDViewsPrep.tsx
  src/components/BulkSelectorNetgroupsPrep.tsx
  src/components/BulkSelectorPrep.tsx
  src/components/BulkSelectorServicesPrep.tsx
  src/components/BulkSelectorSudoCmdGroupsPrep.tsx
  src/components/BulkSelectorSudoCmdsPrep.tsx
  src/components/BulkSelectorSudoRulesPrep.tsx
  src/components/BulkSelectorUserGroupsPrep.tsx
  src/components/BulkSelectorUsersPrep.tsx
  src/pages/ActiveUsers/ActiveUsers.tsx
  src/pages/HBACRules/HBACRules.tsx
  src/pages/HBACServiceGroups/HBACServiceGroups.tsx
  src/pages/HBACServices/HBACServices.tsx
  src/pages/HostGroups/HostGroups.tsx
  src/pages/Hosts/Hosts.tsx
  src/pages/IDViews/IDViews.tsx
  src/pages/Netgroups/Netgroups.tsx
  src/pages/PreservedUsers/PreservedUsers.tsx
  src/pages/Services/Services.tsx
  src/pages/StageUsers/StageUsers.tsx
  src/pages/SudoCmdGroups/SudoCmdGroups.tsx
  src/pages/SudoCmds/SudoCmds.tsx
  src/pages/SudoRules/SudoRules.tsx
  src/pages/UserGroups/UserGroups.tsx
Labels: needs-review

#526 Reset password page and functionality
  src/AppLayout.tsx
  src/components/layouts/PasswordInput.tsx
  src/login/LoginMainPage.tsx
  src/login/ResetPasswordPage.tsx
  src/navigation/AppRoutes.tsx
  src/services/rpcAuth.ts
Labels: ack, needs-review

#517 memberOf - fix issues with direct/indirect memberships
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfHostGroups.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/HostGroups/HostGroupsTabs.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/pages/IDViews/IDViewsTabs.tsx
  src/pages/Netgroups/NetgroupsTabs.tsx
  src/pages/Services/ServicesMemberOf.tsx
  src/pages/UserGroups/UserGroupsMemberOf.tsx
  src/pages/UserGroups/UserGroupsTabs.tsx
Labels: needs-review

#533 Fix login page background image
  src/assets/images/login-screen-logo.png
  src/assets/images/product-name.png
  src/index.css
  src/login/LoginMainPage.tsx
  src/login/ResetPasswordPage.tsx
Labels: ack, needs-review
