Repository freeipa/freeipa-webui, pull requests merged in 2024-06, with the labels that each got.

#405 Provide pagination to user main pages
  src/App.tsx
  src/pages/ActiveUsers/ActiveUsers.tsx
  src/pages/PreservedUsers/PreservedUsers.tsx
  src/pages/StageUsers/StageUsers.tsx
Labels: needs-review

#413 Fix inconsistent onFocus behaviour in datetime pickers
  src/components/Form/DateTimeSelector.tsx
Labels: ack

#415 Bump CI Fedora version to 39
  Vagrantfile
  tests/features/active_users_handling.feature
  tests/features/user_details.feature
Labels: ack

#414 Fix 'current_password' required
  src/components/modals/ResetPassword.tsx
  src/services/rpcUsers.ts
  src/store/Global/global-slice.ts
Labels: ack

#411 Provide routes for the 'Hosts' pages
  src/components/MemberOf/MemberOfTable.tsx
  src/navigation/AppRoutes.tsx
  src/pages/Hosts/Hosts.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/pages/Hosts/HostsTable.tsx
  src/pages/Hosts/HostsTabs.tsx
Labels: ack

#421 Fix the breadcrumb routes for 'Is a member of' sections in 'Active users' and 'Hosts' pages
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/Hosts/HostsMemberOf.tsx
Labels: ack

#412 Issue 410 - Host settings implement kebob
  src/components/Form/IpaCertificates.tsx
  src/components/UserSettings.tsx
  src/components/layouts/ModalWithTextAreaLayout.tsx
  src/components/modals/HostSetPassword.tsx
  src/components/modals/IssueNewCertificate.tsx
  src/pages/Hosts/HostsSettings.tsx
  src/services/rpcCerts.ts
  src/services/rpcHosts.ts
  tests/features/host_handling.feature
Labels: ack

#418 Issue 417 - Implement HBAC Services main page
  src/components/BulkSelectorHBACServicesPrep.tsx
  src/components/modals/AddHBACService.tsx
  src/components/modals/DeleteHBACService.tsx
  src/pages/HBACServices/HBACServices.tsx
  src/pages/HBACServices/HBACServicesTable.tsx
  src/services/rpc.ts
  src/services/rpcHBAC.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/utils.tsx
  tests/features/hbac_rules_handling.feature
  tests/features/hbac_services_handling.feature
  tests/features/steps/common.ts
Labels: ack

#422 [Hosts][Is a member of'] Implementation of 'Host groups' section
  src/components/MemberOf/MemberOfHostGroups.tsx
  src/components/MemberOf/MemberOfTableHostGroups.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/services/rpcHosts.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/hostUtils.tsx
Labels: needs-review

#423 Provide pagination, search, and membership direction parameters
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSubIds.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
Labels: needs-review

#420 Issue 419 - Implement HBAC service groups main page
  src/components/BulkSelectorHBACSvcGroupPrep.tsx
  src/components/modals/AddHBACServiceGroup.tsx
  src/components/modals/DeleteHBACServiceGroup.tsx
  src/pages/HBACServiceGroups/HBACServiceGroups.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsTable.tsx
  src/services/rpc.ts
  src/services/rpcHBAC.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/utils.tsx
  tests/features/hbac_svc_grp_handling.feature
Labels: needs-review

#425 [Hosts][Is a member of] Implementation of 'Netgroups' section
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/utils/datatypes/globalDataTypes.ts
  src/utils/hostUtils.tsx
Labels: ack

#426 [Hosts][Is a member of] Implementation of 'Roles' section
  src/components/MemberOf/MemberOfRoles.tsx
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/utils/datatypes/globalDataTypes.ts
  src/utils/hostUtils.tsx
Labels: ack

#427 [Hosts][Is a member of] Implementation of 'HBAC rules' section
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/pages/ActiveUsers/UserMemberOf.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/utils/datatypes/globalDataTypes.ts
  src/utils/hostUtils.tsx
Labels: ack

#429 Provide custom hook to handle parameters
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
  src/hooks/useRoutingParams.tsx
Labels: ack

#432 [Active users][Is a member of] Fix showing incorrect data when adding new memberships
  src/components/MemberOf/MemberOfUserGroups.tsx
Labels: ack

#438 Change custom hook name `useRoutingParams`
  src/components/MemberOf/MemberOfHbacRules.tsx
  src/components/MemberOf/MemberOfNetgroups.tsx
  src/components/MemberOf/MemberOfRoles.tsx
  src/components/MemberOf/MemberOfSudoRules.tsx
  src/components/MemberOf/MemberOfUserGroups.tsx
  src/hooks/useListPageSearchParams.tsx
Labels: ack

#433 [Hosts][Is a member of][Host groups] Fix showing incorrect data on add and delete
  src/components/MemberOf/MemberOfHostGroups.tsx
  src/components/MemberOf/MemberOfTableHostGroups.tsx
Labels: ack

#430 [Hosts][Is a member of][Host groups] Implement URL params
  src/components/MemberOf/MemberOfHostGroups.tsx
Labels: ack

#431 [Hosts][Is managed by] Adapt section to use real data + refactor
  src/components/ManagedBy/ManagedByHosts.tsx
  src/components/ManagedBy/ManagedByTableHosts.tsx
  src/components/MemberOf/MemberOfToolbar.tsx
  src/pages/Hosts/HostsManagedBy.tsx
  src/services/rpcHosts.ts
Labels: ack, needs-review

#434 [Services] Provide routes for sections
  src/hooks/useServiceSettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/Services/ServicesMemberOf.tsx
  src/pages/Services/ServicesTable.tsx
  src/pages/Services/ServicesTabs.tsx
  src/services/rpcServices.ts
Labels: ack

#439 [Hosts][Is a member of] Fix subpages not being loaded at refresh
  src/pages/Hosts/HostsManagedBy.tsx
  src/pages/Hosts/HostsMemberOf.tsx
  src/pages/Hosts/HostsTabs.tsx
Labels: ack

#440 [Hosts][Is managed by] Provide URL params
  src/components/ManagedBy/ManagedByHosts.tsx
  src/pages/Hosts/HostsManagedBy.tsx
Labels: ack

#441 User pages: Use custom hook to manage URL params
  src/pages/ActiveUsers/ActiveUsers.tsx
  src/pages/PreservedUsers/PreservedUsers.tsx
  src/pages/StageUsers/StageUsers.tsx
Labels: ack

#442 Hosts: Use custom hook to manage URL params
  src/pages/Hosts/Hosts.tsx
Labels: ack
