Repository freeipa/freeipa-webui, pull requests merged in 2025-09, with the labels that each got.

#833 Remove src/utils/data/GroupRepositories.ts
  src/utils/data/GroupRepositories.ts
Labels: needs-review

#831 Add tests for hbac service group handling and group members
  cypress/e2e/common/ui/dual_list.ts
  cypress/e2e/common/ui/tab.ts
  cypress/e2e/hbac/hbac_rule/hbac_rule.ts
  cypress/e2e/hbac/hbac_service_group/hbac_service_group.feature
  cypress/e2e/hbac/hbac_service_group/hbac_service_group.ts
  cypress/e2e/hbac/hbac_service_group/hbac_service_group_members.feature
  src/components/layouts/DualListLayout/DualListLayout.tsx
  src/components/layouts/DualListSelectorGeneric.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsMembers.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsTabs.tsx
Labels: needs-review

#810 Add eslint react plugin
  eslint.config.mjs
  package-lock.json
  package.json
Labels: WIP, ack

#854 Fix: shellcheck errors
  fix-spec.sh
Labels: ack

#840 Better cypress validation
  cypress/e2e/automember/automember_hostgroup.ts
  cypress/e2e/common/authentication.ts
  cypress/e2e/common/data_tables.ts
  cypress/e2e/common/members_table.ts
  cypress/e2e/dns/dnszones.feature
  cypress/e2e/dns/dnszones.ts
  cypress/e2e/hbac/hbac_service/hbac_service.ts
  cypress/e2e/hbac/hbac_service/hbac_service_is_member_of.feature
  cypress/e2e/hbac/hbac_service/hbac_service_settings.feature
  cypress/e2e/hbac/hbac_service_group/hbac_service_group.feature
  cypress/e2e/hbac/hbac_service_group/hbac_service_group.ts
  cypress/e2e/hbac/hbac_service_group/hbac_service_group_members.feature
  cypress/e2e/hbac/hbac_service_group/hbac_service_group_settings.feature
  cypress/e2e/hbac/hbac_svc_grp/hbac_svc_grp.feature
  cypress/e2e/hbac/hbac_svc_grp/hbac_svc_grp.ts
  cypress/e2e/hbac/hbac_svc_grp/hbac_svc_grp_members.feature
  cypress/e2e/hostgroups/hostgroup.feature
  cypress/e2e/id_views/id_views.feature
  cypress/e2e/netgroup/netgroup_member_of.feature
  cypress/e2e/netgroup/netgroup_settings.feature
  cypress/e2e/user_groups/user_groups_member_manager.feature
  cypress/e2e/user_groups/user_groups_memberof.feature
  cypress/e2e/user_groups/user_groups_members.feature
  src/components/Form/Field.tsx
  src/components/Form/IpaSelect/IpaSelect.tsx
  src/components/UsersSections/UserSettings.tsx
  src/components/layouts/KebabLayout.tsx
  src/components/modals/AddService.tsx
  src/components/modals/Automember/AddRule.tsx
  src/components/modals/CertificateModals/IssueNewCertificate.tsx
  src/components/modals/CertificateModals/RevokeCertificate.tsx
  src/components/modals/DnsZones/AddDnsRecordsModal.tsx
  src/components/modals/HostModals/AddHost.tsx
  src/components/modals/UserModals/AddOtpToken.tsx
  src/pages/ActiveUsers/ActiveUsers.tsx
  src/pages/CertificateMapping/CertificateMappingSettings.tsx
  src/pages/DNSZones/DnsGlobalConfig.tsx
  src/pages/DNSZones/DnsZonesSettings.tsx
  src/pages/Hosts/Hosts.tsx
  src/pages/Hosts/HostsSettings.tsx
  src/pages/IDViews/IDViews.tsx
  src/pages/IdPReferences/IdpReferencesSettings.tsx
  src/pages/Services/ServicesSettings.tsx
  src/pages/SudoRules/SudoRulesSettings.tsx
  src/pages/UserGroups/UserGroupsSettings.tsx
Labels: needs-review

#859 Simplified Request, Response type
  src/services/rpcAuth.ts
Labels: needs-review
