Repository freeipa/freeipa-webui, pull requests merged in 2025-02, with the labels that each got.

#629 Parse doc URLs to Red.ht format
  src/assets/documentation/documentation-links.json
Labels: documentation, ack, needs-review

#631 Fix failing tests for sudorules and usergroups
  tests/features/steps/common.ts
  tests/features/sudo_rules_settings.feature
  tests/features/usergroup_members.feature
Labels: needs-review

#640 Doc: Add default credentials
  README.md
Labels: ack

#651 Add Subordinate IDs main page
  src/components/tables/MainTable.tsx
  src/navigation/AppRoutes.tsx
  src/navigation/NavRoutes.ts
  src/pages/SubordinateIDs/SubordinateIDs.tsx
  src/services/rpcSubordinateIDs.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/subIdUtils.tsx
Labels: needs-review

#652 Subordinate ids action buttons
  src/components/modals/SubIdsModals/AddModal.tsx
  src/pages/SubordinateIDs/SubordinateIDs.tsx
  src/services/rpcSubordinateIDs.ts
  src/services/rpcUsers.ts
Labels: ack
