Repository freeipa/freeipa-webui, pull requests merged in 2025-08, with the labels that each got.

#745 Add DnsForwardZone
  src/navigation/AppRoutes.tsx
  src/navigation/NavRoutes.ts
  src/pages/DNSZones/DnsForwardZones.tsx
  src/services/rpc.ts
  src/services/rpcDnsForwardZones.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/dnsForwardZonesUtils.tsx
  src/utils/utils.tsx
Labels: needs-review

#778 Add test for Popover With Icon Layout
  src/components/layouts/PopoverWithIconLayout/PopoverWithIconLayout.test.tsx
  src/components/layouts/PopoverWithIconLayout/PopoverWithIconLayout.tsx
  src/components/layouts/PopoverWithIconLayout/index.ts
Labels: ack, tests

#784 Fix: Pagination not working in some tables
  src/pages/CertificateMapping/CertificateMapping.tsx
  src/pages/DNSZones/DnsZones.tsx
Labels: needs-review

#786 Dual list refactor
  src/components/layouts/DualListLayout/DualListLayout.test.tsx
  src/components/layouts/DualListLayout/DualListLayout.tsx
  src/components/modals/KeytabElementsDeleteModal.tsx
Labels: ack

#785 Fix: add screen reader text to table headers for accessibility
  src/components/tables/MainTable.tsx
  src/components/tables/UsersTable.tsx
  src/pages/AutoMemUserRules/AutomemRulesTable.tsx
  src/pages/HBACRules/HBACRulesTable.tsx
  src/pages/HBACServiceGroups/HBACServiceGroupsTable.tsx
  src/pages/HBACServices/HBACServicesTable.tsx
  src/pages/HostGroups/HostGroupsTable.tsx
  src/pages/Hosts/HostsTable.tsx
  src/pages/IDViews/IDViewsTable.tsx
  src/pages/Netgroups/NetgroupsTable.tsx
  src/pages/Services/ServicesTable.tsx
  src/pages/SudoCmdGroups/SudoCmdGroupsTable.tsx
  src/pages/SudoCmds/SudoCmdsTable.tsx
  src/pages/SudoRules/SudoRulesTable.tsx
  src/pages/UserGroups/UserGroupsTable.tsx
Labels: ack

#804 Add update dns button
  src/components/modals/HostModals/DeleteHosts.tsx
  src/services/rpcHosts.ts
Labels: ack

#813 Rename release of webui to modern-ui
  Makefile.am
Labels: ack

#802 Add simple subids cypress tests
  cypress/e2e/common/ui/select.ts
  cypress/e2e/subids/subids.feature
  cypress/e2e/subids/subids.ts
  cypress/e2e/subids/subids_settings.feature
Labels: ack

#799 Cypress host
  cypress.config.ts
  cypress/e2e/common/host_management.ts
  cypress/e2e/hosts/hosts.feature
  src/components/modals/HostModals/AddHost.tsx
Labels: ack
