Repository freeipa/freeipa-webui, pull requests merged in 2025-03, with the labels that each got.

#658 Add IpaSshPublicKeys unit tests
  src/components/Form/IpaSshPublicKeys/IpaSshPublicKeys.test.tsx
  src/components/Form/IpaSshPublicKeys/IpaSshPublicKeys.tsx
  src/components/HostsSections/HostSettings.tsx
  src/components/UsersSections/UsersAccountSettings.tsx
Labels: needs-review

#660 Fix: Subordinate IDs duplicated files
  src/components/modals/SubIdsModals/AddModal.tsx
  src/pages/SubordinateIDs/SubIdsStatistics.tsx
  src/pages/SubordinateIDs/SubordinateIDs.tsx
  src/services/rpcSubIds.ts
  src/services/rpcSubordinateIDs.ts
  src/utils/subIdsUtils.ts
Labels: ack

#659 Change icon importing
  src/AppLayout.tsx
  src/components/ContextualHelpPanel/ContextualHelpPanel.tsx
  src/components/Form/IpaCertificateMappingData.tsx
  src/components/HostsSections/Enrollment.tsx
  src/components/ManagedBy/ManagedByTable.tsx
  src/components/ManagedBy/ManagedByToolbar.tsx
  src/components/MemberOf/MemberOfSubIdToolbar.tsx
  src/components/MemberOf/MemberOfToolbar.tsx
  src/components/MemberOf/MemberOfToolbarOld.tsx
  src/components/ServicesSections/Provisioning.tsx
  src/components/TypeAheadSelectWithCreate.tsx
  src/components/errors/PageErrors.tsx
  src/components/layouts/DualListLayout.tsx
  src/components/layouts/ExpandableCardLayout.tsx
  src/components/layouts/HelpTextWithIconLayout.tsx
  src/components/layouts/KebabLayout.tsx
  src/components/layouts/PasswordInput.tsx
  src/components/layouts/PopoverWithIconLayout.tsx
  src/components/modals/UserModals/AddUser.tsx
  src/components/tables/EmptyBodyTable.tsx
  src/login/LoginMainPage.tsx
  src/pages/ActiveUsers/ActiveUsersTabs.tsx
  src/pages/AutoMemUserRules/AutoMemSettings.tsx
  src/pages/HBACRules/HBACRulesSettings.tsx
  src/pages/IDViews/IDViewsOverrideGroups.tsx
  src/pages/IDViews/IDViewsSettings.tsx
Labels: needs-review

#664 Use TypeScript generics in 'BulkSelectorPrep' component
  src/components/BulkSelectorPrep.tsx
Labels: ack

#667 Password policy > 'Settings' page
  src/hooks/usePwPolicySettingsData.tsx
  src/navigation/AppRoutes.tsx
  src/pages/PasswordPolicies/PasswordPolicies.tsx
  src/pages/PasswordPolicies/PasswordPoliciesSettings.tsx
  src/pages/PasswordPolicies/PasswordPoliciesTabs.tsx
  src/services/rpcPwdPolicies.ts
Labels: needs-review

#670 Ipacertificates unit tests
  src/components/Form/IpaCertificates/IpaCertificates.test.tsx
  src/components/Form/IpaCertificates/IpaCertificates.tsx
  src/components/HostsSections/HostCertificate.tsx
  src/components/ServicesSections/ServiceCertificate.tsx
  src/components/UsersSections/UsersAccountSettings.tsx
  src/components/modals/CertificateModals/CertificatesInformationModal.tsx
  src/components/modals/CertificateModals/RemoveHoldCertificate.tsx
  src/components/modals/CertificateModals/RevokeCertificate.tsx
  src/utils/datatypes/globalDataTypes.ts
Labels: needs-review

#671 Add 'Kerberos ticket policy' page
  src/components/layouts/PageWithGrayBorderLayout.tsx
  src/hooks/useKrbTicketPolicyData.tsx
  src/pages/KrbTicketPolicy/KrbTicketPolicy.tsx
  src/services/rpcKrbTicketPolicy.ts
  src/utils/datatypes/globalDataTypes.ts
  src/utils/krbTicketUtils.tsx
Labels: ack

#672 'Kerberos ticket policy' integration test
  src/pages/KrbTicketPolicy/KrbTicketPolicy.tsx
  src/services/rpcKrbTicketPolicy.ts
  tests/features/krbtpolicy_handling.feature
Labels: needs-review, tests

#674 'Identity Provider references' main page
  src/navigation/AppRoutes.tsx
  src/navigation/NavRoutes.ts
  src/pages/IdPReferences/IdpReferences.tsx
  src/services/rpcIdp.ts
  src/utils/ipdServerUtils.tsx
  src/utils/utils.tsx
Labels: ack

#682 [Identity Provider references] Fix radio buttons not working in the 'Add' modal
  src/components/modals/IdpReferences/AddModal.tsx
Labels: ack, needs-review

#657 Replace WebPack build with Vite
  .eslintignore
  README.md
  Vagrantfile
  index.dev.html
  index.html
  package-lock.json
  package.json
  public/images/header-logo.png
  src/AppLayout.tsx
  src/assets/images/avatarImg.svg
  src/declarationFiles.d.ts
  src/main.css
  src/main.tsx
  src/navigation/NavRoutes.ts
  src/pages/SetupBrowserConfig.tsx
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  webpack.config.js
Labels: needs-review

#685 Align current version with `package-lock.json` file
  package-lock.json
Labels: needs-review
